  - name: install unzip
    package:
      name: unzip

  - name: Install Nagios (CentOS)
    unarchive:
      src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Install Nagios Package (CentOS)
    tags: centOS, nagios
    dnf:
      name:
        - php-gd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


